// Code generated by wit-bindgen-go. DO NOT EDIT.

package events

import (
	"go.bytecodealliance.org/cm"
)

func lower_PluginEvent(v PluginEvent) (f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) {
	f0, f1 = cm.LowerString(v.Kind)
	f2, f3 = cm.LowerList(v.Payload)
	return
}
