// Code generated by wit-bindgen-go. DO NOT EDIT.

package events

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hellohq:plugin@0.1.0".

//go:wasmimport hellohq:plugin/events@0.1.0 emit
//go:noescape
func wasmimport_Emit(event0 *uint8, event1 uint32, event2 *uint8, event3 uint32, result *cm.Result[APIError, struct{}, APIError])
