// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package events represents the imported interface "hellohq:plugin/events@0.1.0".
//
// ── Push events (plugin → host; size + rate capped) ──────────────────────────
// Plugin → host. Host applies a size + rate cap before forwarding.
package events

import (
	"github.com/HelloHQ/plugin-sdk/sdks/go/internal/bindings/hellohq/plugin/types"
	"go.bytecodealliance.org/cm"
)

// APIError represents the type alias "hellohq:plugin/events@0.1.0#api-error".
//
// See [types.APIError] for more information.
type APIError = types.APIError

// PluginEvent represents the record "hellohq:plugin/events@0.1.0#plugin-event".
//
//	record plugin-event {
//		kind: string,
//		payload: list<u8>,
//	}
type PluginEvent struct {
	_       cm.HostLayout  `json:"-"`
	Kind    string         `json:"kind"`
	Payload cm.List[uint8] `json:"payload"`
}

// Emit represents the imported function "emit".
//
//	emit: func(event: plugin-event) -> result<_, api-error>
//
//go:nosplit
func Emit(event PluginEvent) (result cm.Result[APIError, struct{}, APIError]) {
	event0, event1, event2, event3 := lower_PluginEvent(event)
	wasmimport_Emit((*uint8)(event0), (uint32)(event1), (*uint8)(event2), (uint32)(event3), &result)
	return
}
