#!/usr/bin/env python3
"""Bundle the ``wallet_tracker`` package + ``plugin.py`` into one sidecar file.

The Tier-1 sidecar artifact is a single ``plugin.py`` (the manifest's
``wasm_url`` points at it). Internal imports must therefore be removed and the
modules concatenated in dependency order. Rules this relies on (enforced by
tests/test_bundle.py):

* internal imports are written ``from wallet_tracker.<mod> import ...``;
* top-level names are unique across modules;
* ``from __future__`` lines are hoisted once.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

PACKAGE = "wallet_tracker"
ORDER = [
    "errors",
    "host",
    "sdk_host",
    "ratelimit",
    "polite",
    "money",
    "addresses",
    "btc",
    "solana",
    "proposals",
    "tracker",
]
_INTERNAL = re.compile(rf"^from {PACKAGE}(\.\w+)? import (\([^)]*\)|[^\n]*)\n", re.MULTILINE | re.DOTALL)
# Modules other modules use as namespaces (``from wallet_tracker import btc``).
NAMESPACED = ["btc", "solana"]
_FUTURE = re.compile(r"^from __future__ import annotations\n", re.MULTILINE)


def _strip(source: str) -> str:
    source = _FUTURE.sub("", source)
    return _INTERNAL.sub("", source)


def _namespace(name: str, source: str) -> str:
    names: list[str] = []
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            names.append(node.name)
        elif isinstance(node, ast.Assign):
            names += [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.append(node.target.id)
    listed = ", ".join(repr(n) for n in names)
    return f"\n{name} = _types.SimpleNamespace(**{{n: globals()[n] for n in ({listed},)}})\n"


def build(root: Path) -> str:
    parts = [
        '"""Bundled single-file sidecar (generated by bundle.py - do not edit)."""\n',
        "from __future__ import annotations\n\nimport types as _types\n",
    ]
    for name in ORDER:
        text = (root / PACKAGE / f"{name}.py").read_text()
        parts.append(f"\n# ---- {PACKAGE}.{name} " + "-" * 40 + "\n" + _strip(text))
        if name in NAMESPACED:
            parts.append(_namespace(name, text))
    parts.append("\n# ---- plugin " + "-" * 40 + "\n" + _strip((root / "plugin.py").read_text()))
    return "".join(parts)


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else here / "dist" / "plugin.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build(here))
    print(out)
