// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package hellohqplugincomponent represents the world "hellohq:plugin/hellohq-plugin-component@0.1.0".
//
// SDK-local supplementary build world — NOT part of the plugin-protocol SSOT.
//
// wit-bindgen-go (v0.7.0) + TinyGo (0.41.x) cannot yet bind the WASI-0.3
// `stream<string>` returned by the canonical `inference.complete`:
//
// complete: func(..) -> result<stream<string>, api-error>
//
// `wit-bindgen-go generate` against the full `hellohq-plugin` world fails on the
// async `stream`/`future` machinery (no `cm`-package codegen for WASI 0.3 async
// in v0.7.0). This world imports the SAME canonical `hellohq:plugin/*@0.1.0`
// interfaces MINUS `inference`. Interface identities are unchanged: a component
// built against this world imports `hellohq:plugin/{types,workspace,storage,
// events,log}@0.1.0`, exactly what the host implements and permission-gates for
// a Rust guest. This mirrors the JS SDK's `hellohq-plugin-component` world and
// the Rust SDK's `guest.run`-is-sync split.
//
// This file intentionally has NO `package` declaration — it inherits the
// `hellohq:plugin@0.1.0` package from `hellohq-plugin.wit` in this directory.
// When TinyGo + wit-bindgen-go gain WASI-0.3 `stream` support, Go plugins can
// build against the canonical `hellohq-plugin` world directly and this file can
// be retired.
package hellohqplugincomponent
