"""Bundle the ``property_estimates`` package + ``plugin.py`` into one sidecar file.

The registry artifact for a Tier-1 plugin is a single ``plugin.py``, so the package is
concatenated in dependency order with its intra-package imports removed. Module-level names
are unique across modules by convention (region modules prefix theirs: ``sg_``, ``uk_``...)
and ``tests/test_bundle.py`` executes the bundle to prove it.

Usage: python bundle.py [out_path]   (default: dist/plugin.py)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
PACKAGE = "filings_companion"
ORDER = [
    "errors", "ratelimit", "hostapi", "identifiers", "contact", "money", "transport",
    "sec", "openfigi", "service",
]  # fmt: skip
_OWN_IMPORT = re.compile(rf"^from (\.[\w.]*|{PACKAGE}[\w.]*) import ")


def _strip(source: str, name: str) -> str:
    """Drop ``from __future__`` and intra-package imports (single or parenthesised)."""
    out: list[str] = []
    skipping = False
    for line in source.splitlines():
        if skipping:
            skipping = line.strip() != ")"
            continue
        if line.startswith("from __future__"):
            continue
        if _OWN_IMPORT.match(line):
            skipping = line.rstrip().endswith("(")
            continue
        out.append(line)
    if skipping:
        raise SystemExit(f"{name}: unterminated import")
    return "\n".join(out).strip("\n")


def build() -> str:
    parts = ['"""Single-file sidecar bundle (generated by bundle.py). Do not edit."""', "",
             "from __future__ import annotations", ""]  # fmt: skip
    for name in ORDER:
        parts += [
            f"# ---- {PACKAGE}/{name}.py " + "-" * 40,
            _strip((ROOT / PACKAGE / f"{name}.py").read_text(), name),
            "",
        ]
    parts += ["# ---- plugin.py " + "-" * 50,
              _strip((ROOT / "plugin.py").read_text(), "plugin.py"), ""]  # fmt: skip
    return "\n".join(parts)


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "dist" / "plugin.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out}")
