// Code generated by wit-bindgen-go. DO NOT EDIT.

package workspace

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// APIErrorShape is used for storage in variant or result types.
type APIErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(APIError{})]byte
}

// SheetSummaryShape is used for storage in variant or result types.
type SheetSummaryShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(SheetSummary{})]byte
}

// AssetCountShape is used for storage in variant or result types.
type AssetCountShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(AssetCount{})]byte
}

// AggregatedSummaryShape is used for storage in variant or result types.
type AggregatedSummaryShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(AggregatedSummary{})]byte
}
