// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package workspace represents the imported interface "hellohq:plugin/workspace@0.1.0".
//
// ── Workspace reads (read-only, permission-gated per function) ──────────────
// Read-only, permission-gated per function; `read-aggregated-values` requires
// Verified trust + per-portfolio scope.
package workspace

import (
	"github.com/HelloHQ/plugin-sdk/sdks/go/internal/bindings/hellohq/plugin/types"
	"go.bytecodealliance.org/cm"
)

// APIError represents the type alias "hellohq:plugin/workspace@0.1.0#api-error".
//
// See [types.APIError] for more information.
type APIError = types.APIError

// PortfolioName represents the type alias "hellohq:plugin/workspace@0.1.0#portfolio-name".
//
// See [types.PortfolioName] for more information.
type PortfolioName = types.PortfolioName

// SheetSummary represents the type alias "hellohq:plugin/workspace@0.1.0#sheet-summary".
//
// See [types.SheetSummary] for more information.
type SheetSummary = types.SheetSummary

// AssetCount represents the type alias "hellohq:plugin/workspace@0.1.0#asset-count".
//
// See [types.AssetCount] for more information.
type AssetCount = types.AssetCount

// CurrencyRate represents the type alias "hellohq:plugin/workspace@0.1.0#currency-rate".
//
// See [types.CurrencyRate] for more information.
type CurrencyRate = types.CurrencyRate

// AggregatedSummary represents the type alias "hellohq:plugin/workspace@0.1.0#aggregated-summary".
//
// See [types.AggregatedSummary] for more information.
type AggregatedSummary = types.AggregatedSummary

// ReadPortfolioNames represents the imported function "read-portfolio-names".
//
//	read-portfolio-names: func() -> result<list<portfolio-name>, api-error>
//
//go:nosplit
func ReadPortfolioNames() (result cm.Result[APIErrorShape, cm.List[PortfolioName], APIError]) {
	wasmimport_ReadPortfolioNames(&result)
	return
}

// ReadSheetStructure represents the imported function "read-sheet-structure".
//
//	read-sheet-structure: func(portfolio-id: string) -> result<sheet-summary, api-error>
//
//go:nosplit
func ReadSheetStructure(portfolioID string) (result cm.Result[SheetSummaryShape, SheetSummary, APIError]) {
	portfolioId0, portfolioId1 := cm.LowerString(portfolioID)
	wasmimport_ReadSheetStructure((*uint8)(portfolioId0), (uint32)(portfolioId1), &result)
	return
}

// ReadAssetCount represents the imported function "read-asset-count".
//
//	read-asset-count: func(portfolio-id: string) -> result<asset-count, api-error>
//
//go:nosplit
func ReadAssetCount(portfolioID string) (result cm.Result[AssetCountShape, AssetCount, APIError]) {
	portfolioId0, portfolioId1 := cm.LowerString(portfolioID)
	wasmimport_ReadAssetCount((*uint8)(portfolioId0), (uint32)(portfolioId1), &result)
	return
}

// ReadCurrencyRates represents the imported function "read-currency-rates".
//
//	read-currency-rates: func() -> result<list<currency-rate>, api-error>
//
//go:nosplit
func ReadCurrencyRates() (result cm.Result[APIErrorShape, cm.List[CurrencyRate], APIError]) {
	wasmimport_ReadCurrencyRates(&result)
	return
}

// ReadAggregatedValues represents the imported function "read-aggregated-values".
//
//	read-aggregated-values: func(portfolio-id: string) -> result<aggregated-summary,
//	api-error>
//
//go:nosplit
func ReadAggregatedValues(portfolioID string) (result cm.Result[AggregatedSummaryShape, AggregatedSummary, APIError]) {
	portfolioId0, portfolioId1 := cm.LowerString(portfolioID)
	wasmimport_ReadAggregatedValues((*uint8)(portfolioId0), (uint32)(portfolioId1), &result)
	return
}

// WriteExternalFile represents the imported function "write-external-file".
//
// write:external_output — RESERVED (no Tier-2 wiring yet); shape reserved so
// adding it later is non-breaking.
//
//	write-external-file: func(filename: string, content: list<u8>) -> result<_, api-error>
//
//go:nosplit
func WriteExternalFile(filename string, content cm.List[uint8]) (result cm.Result[APIError, struct{}, APIError]) {
	filename0, filename1 := cm.LowerString(filename)
	content0, content1 := cm.LowerList(content)
	wasmimport_WriteExternalFile((*uint8)(filename0), (uint32)(filename1), (*uint8)(content0), (uint32)(content1), &result)
	return
}
