// Code generated by wit-bindgen-go. DO NOT EDIT.

package workspace

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hellohq:plugin@0.1.0".

//go:wasmimport hellohq:plugin/workspace@0.1.0 read-portfolio-names
//go:noescape
func wasmimport_ReadPortfolioNames(result *cm.Result[APIErrorShape, cm.List[PortfolioName], APIError])

//go:wasmimport hellohq:plugin/workspace@0.1.0 read-sheet-structure
//go:noescape
func wasmimport_ReadSheetStructure(portfolioId0 *uint8, portfolioId1 uint32, result *cm.Result[SheetSummaryShape, SheetSummary, APIError])

//go:wasmimport hellohq:plugin/workspace@0.1.0 read-asset-count
//go:noescape
func wasmimport_ReadAssetCount(portfolioId0 *uint8, portfolioId1 uint32, result *cm.Result[AssetCountShape, AssetCount, APIError])

//go:wasmimport hellohq:plugin/workspace@0.1.0 read-currency-rates
//go:noescape
func wasmimport_ReadCurrencyRates(result *cm.Result[APIErrorShape, cm.List[CurrencyRate], APIError])

//go:wasmimport hellohq:plugin/workspace@0.1.0 read-aggregated-values
//go:noescape
func wasmimport_ReadAggregatedValues(portfolioId0 *uint8, portfolioId1 uint32, result *cm.Result[AggregatedSummaryShape, AggregatedSummary, APIError])

//go:wasmimport hellohq:plugin/workspace@0.1.0 write-external-file
//go:noescape
func wasmimport_WriteExternalFile(filename0 *uint8, filename1 uint32, content0 *uint8, content1 uint32, result *cm.Result[APIError, struct{}, APIError])
