// Code generated by wit-bindgen-go. DO NOT EDIT.

package storage

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// APIErrorShape is used for storage in variant or result types.
type APIErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(APIError{})]byte
}
