// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package storage represents the imported interface "hellohq:plugin/storage@0.1.0".
//
// ── Key-value storage (plugin:storage) ───────────────────────────────────────
// Host-keyed (plugin_id, key); per-plugin quota enforced host-side.
package storage

import (
	"github.com/HelloHQ/plugin-sdk/sdks/go/internal/bindings/hellohq/plugin/types"
	"go.bytecodealliance.org/cm"
)

// APIError represents the type alias "hellohq:plugin/storage@0.1.0#api-error".
//
// See [types.APIError] for more information.
type APIError = types.APIError

// Get represents the imported function "get".
//
//	get: func(key: string) -> result<option<list<u8>>, api-error>
//
//go:nosplit
func Get(key string) (result cm.Result[APIErrorShape, cm.Option[cm.List[uint8]], APIError]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(key0), (uint32)(key1), &result)
	return
}

// Set represents the imported function "set".
//
//	set: func(key: string, value: list<u8>) -> result<_, api-error>
//
//go:nosplit
func Set(key string, value cm.List[uint8]) (result cm.Result[APIError, struct{}, APIError]) {
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerList(value)
	wasmimport_Set((*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// Delete represents the imported function "delete".
//
//	delete: func(key: string) -> result<_, api-error>
//
//go:nosplit
func Delete(key string) (result cm.Result[APIError, struct{}, APIError]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Delete((*uint8)(key0), (uint32)(key1), &result)
	return
}

// Clear represents the imported function "clear".
//
//	clear: func() -> result<_, api-error>
//
//go:nosplit
func Clear() (result cm.Result[APIError, struct{}, APIError]) {
	wasmimport_Clear(&result)
	return
}

// ListKeys represents the imported function "list-keys".
//
//	list-keys: func() -> result<list<string>, api-error>
//
//go:nosplit
func ListKeys() (result cm.Result[APIErrorShape, cm.List[string], APIError]) {
	wasmimport_ListKeys(&result)
	return
}
