// Code generated by wit-bindgen-go. DO NOT EDIT.

package storage

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hellohq:plugin@0.1.0".

//go:wasmimport hellohq:plugin/storage@0.1.0 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Result[APIErrorShape, cm.Option[cm.List[uint8]], APIError])

//go:wasmimport hellohq:plugin/storage@0.1.0 set
//go:noescape
func wasmimport_Set(key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[APIError, struct{}, APIError])

//go:wasmimport hellohq:plugin/storage@0.1.0 delete
//go:noescape
func wasmimport_Delete(key0 *uint8, key1 uint32, result *cm.Result[APIError, struct{}, APIError])

//go:wasmimport hellohq:plugin/storage@0.1.0 clear
//go:noescape
func wasmimport_Clear(result *cm.Result[APIError, struct{}, APIError])

//go:wasmimport hellohq:plugin/storage@0.1.0 list-keys
//go:noescape
func wasmimport_ListKeys(result *cm.Result[APIErrorShape, cm.List[string], APIError])
