// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "hellohq:plugin/guest@0.1.0".
var Exports struct {
	// Init represents the caller-defined, exported function "init".
	//
	//	init: func()
	Init func()

	// Run represents the caller-defined, exported function "run".
	//
	//	run: func(input: list<u8>) -> result<list<u8>, string>
	Run func(input cm.List[uint8]) (result cm.Result[cm.List[uint8], cm.List[uint8], string])

	// Metadata represents the caller-defined, exported function "metadata".
	//
	//	metadata: func() -> plugin-metadata
	Metadata func() (result PluginMetadata)
}
