// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package guest represents the exported interface "hellohq:plugin/guest@0.1.0".
//
// ── Plugin exports ─────────────────────────────────────────────────────────
package guest

import (
	"go.bytecodealliance.org/cm"
)

// PluginMetadata represents the record "hellohq:plugin/guest@0.1.0#plugin-metadata".
//
//	record plugin-metadata {
//		id: string,
//		version: string,
//	}
type PluginMetadata struct {
	_       cm.HostLayout `json:"-"`
	ID      string        `json:"id"`
	Version string        `json:"version"`
}
