// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "hellohq:plugin@0.1.0".

//go:wasmexport hellohq:plugin/guest@0.1.0#init
//export hellohq:plugin/guest@0.1.0#init
func wasmexport_Init() {
	Exports.Init()
	return
}

//go:wasmexport hellohq:plugin/guest@0.1.0#run
//export hellohq:plugin/guest@0.1.0#run
func wasmexport_Run(input0 *uint8, input1 uint32) (result *cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	input := cm.LiftList[cm.List[uint8]]((*uint8)(input0), (uint32)(input1))
	result_ := Exports.Run(input)
	result = &result_
	return
}

//go:wasmexport hellohq:plugin/guest@0.1.0#metadata
//export hellohq:plugin/guest@0.1.0#metadata
func wasmexport_Metadata() (result *PluginMetadata) {
	result_ := Exports.Metadata()
	result = &result_
	return
}
