#!/usr/bin/env python3
"""Bundle the ``macro_context`` package + ``plugin.py`` into one sidecar file.

The Tier-1 sidecar artifact is a single ``plugin.py`` (the manifest's
``wasm_url`` points at it). Internal imports are removed and modules are
concatenated in dependency order.

The four source modules (ecb, worldbank, treasury, sgfx) intentionally share
function names (``parse_response``, ``request_path``, ``url_for``...), so each
is embedded VERBATIM as a raw string and loaded into its own module object
(``ecb = _load_module("macro_context.ecb", ...)``). The shared modules and
``context``/``plugin`` are inlined as plain code. Rules, enforced by
tests/test_bundle.py:

* internal imports are written ``from macro_context.<mod> import ...``;
* top-level names are unique across the INLINED modules;
* embedded sources contain no ``'''`` and do not end with a backslash.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PACKAGE = "macro_context"
ORDER = [
    "errors",
    "host",
    "sdk_host",
    "ratelimit",
    "polite",
    "money",
    "series",
    "ecb",
    "worldbank",
    "treasury",
    "sgfx",
    "context",
]
EMBEDDED = ["ecb", "worldbank", "treasury", "sgfx"]
_INTERNAL = re.compile(rf"^from {PACKAGE}(\.\w+)? import (\([^)]*\)|[^\n]*)\n", re.MULTILINE | re.DOTALL)
_FUTURE = re.compile(r"^from __future__ import annotations\n", re.MULTILINE)

_LOADER = '''
def _load_module(name, source):
    """Load an embedded source into its own module object (see bundle.py)."""
    module = _types.ModuleType(name)
    module.__dict__.update({k: v for k, v in globals().items() if not k.startswith("__")})
    sys.modules[name] = module
    exec(compile("from __future__ import annotations\\n" + source, f"<{name}>", "exec"), module.__dict__)  # noqa: S102
    return module
'''


def _strip(source: str) -> str:
    return _INTERNAL.sub("", _FUTURE.sub("", source))


def build(root: Path) -> str:
    parts = [
        '"""Bundled single-file sidecar (generated by bundle.py - do not edit)."""\n',
        "from __future__ import annotations\n\nimport sys\nimport types as _types\n",
    ]
    loader_emitted = False
    for name in ORDER:
        text = (root / PACKAGE / f"{name}.py").read_text()
        header = f"\n# ---- {PACKAGE}.{name} " + "-" * 40 + "\n"
        if name in EMBEDDED:
            if not loader_emitted:
                parts.append(_LOADER)
                loader_emitted = True
            body = _strip(text)
            assert "'''" not in body and not body.rstrip("\n").endswith("\\"), f"{name}: cannot embed"
            parts.append(f"{header}{name} = _load_module(\n    \"{PACKAGE}.{name}\",\n    r'''{body}''',\n)\n")
        else:
            parts.append(header + _strip(text))
    parts.append("\n# ---- plugin " + "-" * 40 + "\n" + _strip((root / "plugin.py").read_text()))
    return "".join(parts)


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else here / "dist" / "plugin.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build(here))
    print(out)
