// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "hellohq:plugin/types@0.1.0".
//
// ── Shared types ──────────────────────────────────────────────────────────────
package types

import (
	"go.bytecodealliance.org/cm"
)

// APIError represents the record "hellohq:plugin/types@0.1.0#api-error".
//
// Gate denial, validation failure, or downstream error. Carries no secret,
// raw prompt/response, credential id, or request id (the AI-harness boundary
// rules). `code` is a stable machine token; `message` is safe to show the user.
//
//	record api-error {
//		code: string,
//		message: string,
//	}
type APIError struct {
	_    cm.HostLayout `json:"-"`
	Code string        `json:"code"`

	// "permission-denied" | "origin-blocked" |
	// "address-blocked" | "rate-limited" | "not-found"
	Message string `json:"message"`
}

// PortfolioName represents the record "hellohq:plugin/types@0.1.0#portfolio-name".
//
//	record portfolio-name {
//		id: string,
//		name: string,
//	}
type PortfolioName struct {
	_    cm.HostLayout `json:"-"`
	ID   string        `json:"id"`
	Name string        `json:"name"`
}

// CurrencyRate represents the record "hellohq:plugin/types@0.1.0#currency-rate".
//
//	record currency-rate {
//		id: string,
//		name: string,
//		symbol: string,
//		rate: f64,
//	}
type CurrencyRate struct {
	_  cm.HostLayout `json:"-"`
	ID string        `json:"id"`

	// ISO 4217, e.g. "USD"
	Name   string  `json:"name"`
	Symbol string  `json:"symbol"`
	Rate   float64 `json:"rate"`
}

// SheetInfo represents the record "hellohq:plugin/types@0.1.0#sheet-info".
//
//	record sheet-info {
//		name: string,
//		sections: list<string>,
//	}
type SheetInfo struct {
	_        cm.HostLayout   `json:"-"`
	Name     string          `json:"name"`
	Sections cm.List[string] `json:"sections"`
}

// SheetSummary represents the record "hellohq:plugin/types@0.1.0#sheet-summary".
//
//	record sheet-summary {
//		portfolio-id: string,
//		sheets: list<sheet-info>,
//	}
type SheetSummary struct {
	_           cm.HostLayout      `json:"-"`
	PortfolioID string             `json:"portfolio-id"`
	Sheets      cm.List[SheetInfo] `json:"sheets"`
}

// CategoryCount represents the record "hellohq:plugin/types@0.1.0#category-count".
//
//	record category-count {
//		category: string,
//		count: u32,
//	}
type CategoryCount struct {
	_        cm.HostLayout `json:"-"`
	Category string        `json:"category"`
	Count    uint32        `json:"count"`
}

// AssetCount represents the record "hellohq:plugin/types@0.1.0#asset-count".
//
//	record asset-count {
//		portfolio-id: string,
//		count-by-category: list<category-count>,
//	}
type AssetCount struct {
	_               cm.HostLayout          `json:"-"`
	PortfolioID     string                 `json:"portfolio-id"`
	CountByCategory cm.List[CategoryCount] `json:"count-by-category"`
}

// CategoryTotal represents the record "hellohq:plugin/types@0.1.0#category-total".
//
//	record category-total {
//		category: string,
//		total: f64,
//	}
type CategoryTotal struct {
	_        cm.HostLayout `json:"-"`
	Category string        `json:"category"`
	Total    float64       `json:"total"`
}

// AggregatedSummary represents the record "hellohq:plugin/types@0.1.0#aggregated-summary".
//
//	record aggregated-summary {
//		portfolio-id: string,
//		totals: list<category-total>,
//	}
type AggregatedSummary struct {
	_           cm.HostLayout          `json:"-"`
	PortfolioID string                 `json:"portfolio-id"`
	Totals      cm.List[CategoryTotal] `json:"totals"`
}
