// SPDX-License-Identifier: Apache-2.0

// Package export_wit_world holds the hand-written guest entry for the streaming
// inference quickstart. Everything else in this module is generated by the
// bytecodealliance/wit-bindgen Go backend (regenerate with ./build.sh --gen);
// this file is preserved across regeneration.
package export_wit_world

import (
	inference "wit_component/hellohq_plugin_inference"
	logg "wit_component/hellohq_plugin_log"
	"wit_component/wit_types"
)

// Run is the async streaming-inference entry. It mirrors the Rust SDK's
// inference-quickstart: send one user message, drain the token-delta
// stream<string> concatenating each delta, and return the completion as bytes.
//
// Draining the stream blocks the goroutine, which yields to the host via the
// wasi-on-idle Go runtime while the host produces tokens — exactly what the
// async-lifted `run` export and the readable StreamReader[string] enable.
func Run(input []uint8) wit_types.Result[[]uint8, string] {
	logg.Write(logg.LevelInfo, "component-quickstart-go-inference: run")

	res := inference.Complete(
		[]inference.ChatMessage{
			{Role: "user", Content: "Say hello in three words."},
		},
		inference.InferenceOpts{
			MaxTokens:   64,
			Temperature: wit_types.None[float32](),
		},
	)
	if res.Tag() == wit_types.ResultErr {
		e := res.Err()
		return wit_types.Err[[]uint8, string](e.Code + ": " + e.Message)
	}

	rx := res.Ok() // *wit_types.StreamReader[string]
	defer rx.Drop()

	var text string
	buf := make([]string, 16)
	for !rx.WriterDropped() {
		n := rx.Read(buf)
		for i := uint32(0); i < n; i++ {
			text += buf[i]
		}
	}

	logg.Write(logg.LevelInfo, "component-quickstart-go-inference: stream drained")
	return wit_types.Ok[[]uint8, string]([]uint8(text))
}
