// Code generated by wit-bindgen-go. DO NOT EDIT.

package log

// This file contains wasmimport and wasmexport declarations for "hellohq:plugin@0.1.0".

//go:wasmimport hellohq:plugin/log@0.1.0 write
//go:noescape
func wasmimport_Write(level0 uint32, message0 *uint8, message1 uint32)
