// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package log represents the imported interface "hellohq:plugin/log@0.1.0".
//
// ── Logging (always available, never gated) ────────────────────────────────────
package log

import (
	"go.bytecodealliance.org/cm"
)

// Level represents the enum "hellohq:plugin/log@0.1.0#level".
//
//	enum level {
//		trace,
//		debug,
//		info,
//		warn,
//		error
//	}
type Level uint8

const (
	LevelTrace Level = iota
	LevelDebug
	LevelInfo
	LevelWarn
	LevelError
)

var _LevelStrings = [5]string{
	"trace",
	"debug",
	"info",
	"warn",
	"error",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Level) String() string {
	return _LevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Level) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Level) UnmarshalText(text []byte) error {
	return _LevelUnmarshalCase(e, text)
}

var _LevelUnmarshalCase = cm.CaseUnmarshaler[Level](_LevelStrings[:])

// Write represents the imported function "write".
//
//	write: func(level: level, message: string)
//
//go:nosplit
func Write(level Level, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Write((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
